ci:
  autofix_commit_msg: "[update] 格式化代码"
  autofix_prs: true
  autoupdate_branch: master

repos:
  - repo: https://github.com/hhatto/autopep8
    rev: main
    hooks:
      - id: autopep8
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check commit message
        entry: bash -c 'if ! grep -qE "^\[(add|update|fix|feature|remove)\]" <<< "$1"; then echo "Invalid commit message"; exit 1; fi' --
        language: system
        stages: [commit-msg]