ci:
  autofix_commit_msg: "[update] 格式化代码"
  autofix_prs: true
  autoupdate_branch: master

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--select=E9]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--skip-magic-trailing-comma]
