ci:
  autofix_commit_msg: "[update] 格式化代码"
  autofix_prs: true
  autoupdate_branch: master

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--select=E9]
  - repo: https://github.com/hhatto/autopep8
    rev: main
    hooks:
      - id: autopep8
